import argparse
import csv
import math
from collections import Counter, defaultdict

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch

from common import (
    CLASS_NAMES,
    classify_sequence_error,
    ensure_dir,
    fov_length_group,
    parse_sequence,
    sequence_metrics,
    write_csv,
    zero_to_name,
)


VARIANTS = ["original", "original_post", "crf", "crf_post"]
VARIANT_LABELS = {
    "original": "Original",
    "original_post": "Original-post",
    "crf": "CRF",
    "crf_post": "CRF-post",
}


def parse_args():
    parser = argparse.ArgumentParser(description="Create distinctive sequence-analysis plots for vertebra experiments.")
    parser.add_argument("--csv", required=True, help="CSV generated by crf_evaluation.py.")
    parser.add_argument("--out", required=True, help="Output directory.")
    parser.add_argument("--variant", default="crf_post", choices=VARIANTS, help="Variant used for transition/skyline plots.")
    parser.add_argument("--max-arcs", type=int, default=80, help="Maximum arcs in transition chord plot.")
    return parser.parse_args()


def load_rows(csv_path):
    rows = []
    with open(csv_path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            item = {
                "image_id": str(row.get("image_id", "")),
                "file_name": row.get("file_name", ""),
                "gt_seq": parse_sequence(row.get("gt_seq")),
            }
            for variant in VARIANTS:
                item[variant] = parse_sequence(row.get(variant))
            rows.append(item)
    return rows


def build_summary(rows):
    out = []
    for variant in VARIANTS:
        total = 0
        correct = 0
        ira = 0
        for row in rows:
            m = sequence_metrics(row["gt_seq"], row[variant])
            total += m["num_gt"]
            correct += m["correct"]
            ira += m["ira"]
        out.append({
            "variant": variant,
            "IDR(%)": round(correct / total * 100, 2) if total else 0,
            "IRA(%)": round(ira / len(rows) * 100, 2) if rows else 0,
        })
    return out


def plot_transition_chord(rows, variant, out_dir, max_arcs):
    transitions = Counter()
    for row in rows:
        for gt, pred in zip(row["gt_seq"], row[variant]):
            if gt != pred and 0 <= gt < len(CLASS_NAMES) and 0 <= pred < len(CLASS_NAMES):
                transitions[(gt, pred)] += 1

    top = transitions.most_common(max_arcs)
    n = len(CLASS_NAMES)
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    points = {i: np.array([math.cos(a), math.sin(a)]) for i, a in enumerate(angles)}

    fig, ax = plt.subplots(figsize=(9, 9))
    ax.set_aspect("equal")
    ax.axis("off")

    circle = plt.Circle((0, 0), 1.0, fill=False, color="#D8D8D8", lw=1.2)
    ax.add_artist(circle)
    max_count = max([c for _, c in top], default=1)

    cmap = plt.get_cmap("turbo")
    for i, name in enumerate(CLASS_NAMES):
        p = points[i]
        ax.scatter(p[0], p[1], s=90, color=cmap(i / (n - 1)), edgecolor="white", zorder=4)
        label_pos = p * 1.16
        ax.text(label_pos[0], label_pos[1], name, ha="center", va="center", fontsize=10)

    for (src, dst), count in top:
        start = points[src] * 0.96
        end = points[dst] * 0.96
        width = 0.6 + 4.0 * count / max_count
        rad = 0.25 if (dst - src) % n < n / 2 else -0.25
        color = cmap(src / (n - 1))
        patch = FancyArrowPatch(
            start,
            end,
            connectionstyle=f"arc3,rad={rad}",
            arrowstyle="-|>",
            mutation_scale=8 + 10 * count / max_count,
            lw=width,
            color=color,
            alpha=0.45,
        )
        ax.add_patch(patch)

    ax.text(0, 1.34, f"Misclassification Transition Chord ({VARIANT_LABELS[variant]})",
            ha="center", va="center", fontsize=16, fontweight="bold")
    ax.text(0, -1.27, "Arc direction: ground truth -> prediction", ha="center", fontsize=10, color="#666666")
    plt.tight_layout()
    fig.savefig(out_dir / f"fig_transition_chord_{variant}.png", dpi=300)
    plt.close(fig)

    write_csv(out_dir / f"transition_counts_{variant}.csv", [
        {
            "gt": zero_to_name(src),
            "pred": zero_to_name(dst),
            "count": count,
        }
        for (src, dst), count in transitions.most_common()
    ])


def plot_error_morphology(rows, out_dir):
    error_types = sorted({
        classify_sequence_error(row["gt_seq"], row[v])
        for row in rows
        for v in VARIANTS
    })
    counts = {
        v: Counter(classify_sequence_error(row["gt_seq"], row[v]) for row in rows)
        for v in VARIANTS
    }

    fig, ax = plt.subplots(figsize=(10, 5))
    bottom = np.zeros(len(VARIANTS))
    colors = plt.get_cmap("Set2")(np.linspace(0, 1, len(error_types)))
    for color, err in zip(colors, error_types):
        values = np.array([counts[v].get(err, 0) for v in VARIANTS])
        ax.bar([VARIANT_LABELS[v] for v in VARIANTS], values, bottom=bottom, label=err, color=color)
        bottom += values
    ax.set_ylabel("Number of images")
    ax.set_title("Sequence Error Morphology Across Variants", fontsize=15, fontweight="bold")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.12), ncol=3, fontsize=8)
    ax.spines[["top", "right"]].set_visible(False)
    plt.tight_layout()
    fig.savefig(out_dir / "fig_error_morphology_stack.png", dpi=300)
    plt.close(fig)


def plot_vertebra_error_skyline(rows, variant, out_dir):
    total = Counter()
    wrong = Counter()
    for row in rows:
        for gt, pred in zip(row["gt_seq"], row[variant]):
            total[gt] += 1
            wrong[gt] += int(gt != pred)
    rates = [wrong[i] / total[i] * 100 if total[i] else 0 for i in range(len(CLASS_NAMES))]

    fig, ax = plt.subplots(figsize=(11, 4))
    colors = plt.get_cmap("RdYlBu_r")(np.linspace(0.15, 0.9, len(CLASS_NAMES)))
    ax.fill_between(range(len(CLASS_NAMES)), rates, color="#A6CEE3", alpha=0.35)
    ax.plot(range(len(CLASS_NAMES)), rates, color="#1F78B4", lw=2.5)
    ax.scatter(range(len(CLASS_NAMES)), rates, s=90, c=colors, edgecolor="white", zorder=3)
    for i, value in enumerate(rates):
        ax.text(i, value + 1, f"{value:.1f}", ha="center", fontsize=8)
    ax.set_xticks(range(len(CLASS_NAMES)))
    ax.set_xticklabels(CLASS_NAMES, rotation=45, ha="right")
    ax.set_ylabel("Error rate (%)")
    ax.set_title(f"Vertebra-wise Error Skyline ({VARIANT_LABELS[variant]})", fontsize=15, fontweight="bold")
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="y", alpha=0.25)
    plt.tight_layout()
    fig.savefig(out_dir / f"fig_error_skyline_{variant}.png", dpi=300)
    plt.close(fig)

    write_csv(out_dir / f"vertebra_error_rates_{variant}.csv", [
        {
            "class": CLASS_NAMES[i],
            "num_instances": total[i],
            "num_errors": wrong[i],
            "error_rate(%)": round(rates[i], 2),
        }
        for i in range(len(CLASS_NAMES))
    ])


def plot_fov_radar(rows, out_dir):
    groups = ["short(<=6)", "medium(7-10)", "long(>10)"]
    angles = np.linspace(0, 2 * np.pi, len(groups), endpoint=False).tolist()
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=(7, 7), subplot_kw={"projection": "polar"})
    colors = {
        "original": "#E15759",
        "original_post": "#F28E2B",
        "crf": "#4E79A7",
        "crf_post": "#59A14F",
    }
    for variant in VARIANTS:
        values = []
        for group in groups:
            subset = [row for row in rows if fov_length_group(len(row["gt_seq"])) == group]
            total = correct = 0
            for row in subset:
                m = sequence_metrics(row["gt_seq"], row[variant])
                total += m["num_gt"]
                correct += m["correct"]
            values.append(correct / total * 100 if total else 0)
        values += values[:1]
        ax.plot(angles, values, label=VARIANT_LABELS[variant], color=colors[variant], lw=2.2)
        ax.fill(angles, values, color=colors[variant], alpha=0.08)

    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(groups)
    ax.set_ylim(0, 100)
    ax.set_title("FoV Robustness Radar (IDR)", fontsize=15, fontweight="bold", pad=20)
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.08), ncol=2)
    plt.tight_layout()
    fig.savefig(out_dir / "fig_fov_robustness_radar.png", dpi=300)
    plt.close(fig)


def plot_case_gain_lollipop(rows, out_dir):
    gains = []
    for row in rows:
        before = sequence_metrics(row["gt_seq"], row["original"])["correct"]
        after = sequence_metrics(row["gt_seq"], row["crf_post"])["correct"]
        gains.append((after - before, row["image_id"], before, after, len(row["gt_seq"])))
    gains.sort(reverse=True)
    top = gains[:20]
    labels = [x[1] for x in top]
    y = np.arange(len(top))
    before_vals = [x[2] for x in top]
    after_vals = [x[3] for x in top]

    fig, ax = plt.subplots(figsize=(8, 7))
    for yi, b, a in zip(y, before_vals, after_vals):
        ax.plot([b, a], [yi, yi], color="#BBBBBB", lw=2)
    ax.scatter(before_vals, y, color="#E15759", s=55, label="Original")
    ax.scatter(after_vals, y, color="#59A14F", s=55, label="CRF-post")
    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.invert_yaxis()
    ax.set_xlabel("Correct vertebrae in one image")
    ax.set_ylabel("Image ID")
    ax.set_title("Largest Per-case Correction Gains", fontsize=15, fontweight="bold")
    ax.legend()
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="x", alpha=0.2)
    plt.tight_layout()
    fig.savefig(out_dir / "fig_case_gain_lollipop.png", dpi=300)
    plt.close(fig)

    write_csv(out_dir / "top_case_gains.csv", [
        {
            "image_id": image_id,
            "gain": gain,
            "original_correct": before,
            "crf_post_correct": after,
            "seq_len": seq_len,
        }
        for gain, image_id, before, after, seq_len in top
    ])


def main():
    args = parse_args()
    out_dir = ensure_dir(args.out)
    rows = load_rows(args.csv)
    write_csv(out_dir / "variant_summary.csv", build_summary(rows))
    plot_transition_chord(rows, args.variant, out_dir, args.max_arcs)
    plot_error_morphology(rows, out_dir)
    plot_vertebra_error_skyline(rows, args.variant, out_dir)
    plot_fov_radar(rows, out_dir)
    plot_case_gain_lollipop(rows, out_dir)
    print(f"Saved distinctive sequence plots to {out_dir}")


if __name__ == "__main__":
    main()
